// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtAEHoN9ZucukEX9IRLscxLjAQrCDngD8',
    appId: '1:982946553883:web:b5e3cdf15b4fdd752658be',
    messagingSenderId: '982946553883',
    projectId: 'cafe-d0a51',
    authDomain: 'cafe-d0a51.firebaseapp.com',
    storageBucket: 'cafe-d0a51.firebasestorage.app',
    measurementId: 'G-0TNT3XSPVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOvPbZ8pNRGG8VArQYwkISN9MZBu0rYk',
    appId: '1:982946553883:android:721eea206580ab702658be',
    messagingSenderId: '982946553883',
    projectId: 'cafe-d0a51',
    storageBucket: 'cafe-d0a51.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqA0jtftPyUdqBzptkVJM_divlf6abis',
    appId: '1:982946553883:ios:72dbb7ce938df1ee2658be',
    messagingSenderId: '982946553883',
    projectId: 'cafe-d0a51',
    storageBucket: 'cafe-d0a51.firebasestorage.app',
    iosBundleId: 'y',
  );
}
